name: "Pull Request"

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - name: "Install"
      run: |
        npm install
    - name: "Prettier"
      run: |
        npm run format-check
    - name: "Lint"
      run: |
        npm run lint
    - name: "build"
      run: |
        npm run build
        npm run package

  release:
    runs-on: ubuntu-22.04
    name: "Build and release action"
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          dry_run: true
          token: "${{ secrets.GITHUB_TOKEN }}"
